### ISSUE TITLE
Can not install iotz properly

### ISSUE THREAD

**Issue by michaelchien1972** [Azure/iotz#48]
$ sudo npm i iotz -g
/usr/local/bin/iotz -> /usr/local/lib/node_modules/iotz/index.js

> iotz@0.2.7 postinstall /usr/local/lib/node_modules/iotz
> iotz update

/usr/local/lib/node_modules/iotz/extensions/index.js:174
  for (let file of files) {
       ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:404:25)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/iotz/src/common.js:12:20)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
npm ERR! Linux 4.15.0-34-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "iotz" "-g"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6
npm ERR! code ELIFECYCLE

npm ERR! iotz@0.2.7 postinstall: `iotz update`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the iotz@0.2.7 postinstall script 'iotz update'.
npm ERR! This is most likely a problem with the iotz package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     iotz update
npm ERR! You can get their info via:
npm ERR!     npm owner ls iotz
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/michael/node-v5.0.0/npm-debug.log
michael@michael-linux-work:~/node-v5.0.0$ 

Any idea?

**Comment by obastemur** [comment]
`node v5.0.0`. Can you please try with a recent node.js version?

**Comment by obastemur** [comment]
Closing this for now; if the suggestion above doesn't work for you, please open it back.
