### ISSUE TITLE
iotz init failing on macOS

### ISSUE THREAD

**Issue by andyt530** [Azure/iotz#51]
Have a problem on my MAC with iotz init - some sort of docker issue with being unable to find a Dockerfile  (where is this supposed to come from ?)

az2tf:mxchip_advanced AndyT$ **docker version**
Client: Docker Engine - Community
 Version:           18.09.0
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        4d60db4
 Built:             Wed Nov  7 00:47:43 2018
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.0
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       4d60db4
  Built:            Wed Nov  7 00:55:00 2018
  OS/Arch:          linux/amd64
  Experimental:     true
az2tf:mxchip_advanced AndyT$ 

az2tf:mxchip_advanced AndyT$ **npm version**
{ npm: '6.4.1',
  ares: '1.10.1-DEV',
  cldr: '32.0',
  http_parser: '2.8.0',
  icu: '60.1',
  modules: '57',
  napi: '3',
  nghttp2: '1.32.0',
  node: '8.12.0',
  openssl: '1.0.2p',
  tz: '2017c',
  unicode: '10.0',
  uv: '1.19.2',
  v8: '6.2.414.66',
  zlib: '1.2.11' }
az2tf:mxchip_advanced AndyT$ 

az2tf:mxchip_advanced AndyT$ **npm i iotz -g**
/usr/local/bin/iotz -> /usr/local/lib/node_modules/iotz/index.js
iotz@0.4.0
updated 1 package in 1.087s

az2tf:mxchip_advanced AndyT$ **iotz  update**
updating.. (this may take some time)
latest: Pulling from azureiot/iotz
Digest: sha256:3d46ff59cc96e9915def462e4ce183f1e15cfcd0ebeeedc8a3f7f389541e31f1
Status: Image is up to date for azureiot/iotz:latest
 base container update was succesfull
 updating extensions
 building arduino extension container (it may take some time)

az2tf:mxchip_advanced AndyT$ **iotz init**
AZ3166:stm32f4:MXCHIP_AZ3166 is selected
unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /Users/AndyT/Library/Mobile/Dockerfile: no such file or directory
 error: docker couldn't create an image for this path

**Comment by obastemur** [comment]
Could you try below?

‘’’
rm -rf ~/.iotz
iotz init
‘’’

**Comment by andyt530** [comment]
Unfortunately no joy:

az2tf:mxchip_advanced AndyT$ rm -rf ~/.iotz
az2tf:mxchip_advanced AndyT$ iotz init
 building arduino extension container (it may take some time)
AZ3166:stm32f4:MXCHIP_AZ3166 is selected
unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /Users/AndyT/Library/Mobile/Dockerfile: no such file or directory
 - error: docker couldn't create an image for this path

**Comment by obastemur** [comment]
Possibly your user doesn’t have a write access. Can you try ‘init’ under ‘~/Desktop/mxchip_advanced’ ?

**Comment by andyt530** [comment]
Hi - Yes - Moved forward:

cd ~/Desktop/mxchip_advanced

az2tf:mxchip_advanced AndyT$ rm -rf ~/.iotz
az2tf:mxchip_advanced AndyT$ iotz init
‘’’ - building arduino extension container (it may take some time)
 - AZ3166:stm32f4:MXCHIP_AZ3166 is selected
az2tf:mxchip_advanced AndyT$ iotz compile
Picked up JAVA_TOOL_OPTIONS: 
Loading configuration...
Initializing packages...
Preparing boards..

Verifying...
In file included from sketch/src/../inc/AzureIOTClient.h:9:0,
                 from sketch/src/../inc/telemetry.h:9,
                 from sketch/src/AzureIOTClient.cpp:7:
/root/.arduino15/packages/AZ3166/hardware/stm32f4/1.6.0/libraries/AzureIoT/src/AzureIotHub.h:6:27: fatal error: iothub_client.h: No such file or directory
 #include "iothub_client.h"

I can see that file in :  /Users/AndyT/Library/Arduino15/packages/AZ3166/hardware/stm32f4/1.6.0/cores/arduino/azure-iot-sdk-c/iothub_client/inc/iothub_client.h

How do we get in included in the search path for iotz ?


                           ^

**Comment by obastemur** [comment]
Apparently mxchip firmware folks did couple of breaking changes and broke the include path compile directives. I did mend those on iotz build definitions and I will contact mxchip firmware folks separately.  

First of all, thanks for reporting this. Second; I did release `0.4.1` that you can update to now and use it. 

```
npm i -g iotz
iotz update
```
and under the new `mxchip_advanced` folder

```
iotz init
```

finally

```
iotz compile
```

**Comment by andyt530** [comment]
Yes - that fixed it - thank you
